# C:\Users\Madina\Desktop\fromNew\Dev-X\DevOps\project\helm-chart
apiVersion: v2
name: helm-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - helm-chart
  - helm
maintainers:
  - name: MadinaTad 
    email: madina.tadjidinova@gmail.com