apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: argocd
  labels:
    app: httpd-app
spec:
  selector:
    app: httpd-app
  type: LoadBalancer
  ports:
    - name: httpd
      port: 80
      targetPort: 80