# name: Helm Chart Workflow
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Helm
#         uses: azure/setup-helm@v1
#         with:
#           version: '3.x'

#       - name: Lint Helm chart
#         run: |
#           helm lint /c/Users/Madina/Desktop/fromNew/Dev-X/DevOps/project/helm-chart

#       - name: Package Helm chart
#         run: |
#           helm package /c/Users/Madina/Desktop/fromNew/Dev-X/DevOps/project/helm-chart

#       - name: Push Helm chart to repository
#         run: |
#           helm push /c/Users/Madina/Desktop/fromNew/Dev-X/DevOps/project/helm-chart github.com/MadinaTadjidinova/helm-chart.git

name: Helm Chart Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

      - name: Clone Helm Chart Repository
        run: |
          git clone https://github.com/MadinaTadjidinova/helm-chart.git

      - name: Lint Helm Chart
        run: helm lint helm-chart/

      - name: Package Helm Chart
        run: helm package helm-chart/ --destination output/

      - name: Configure Git
        run: |
          git config --global user.name "Madina Tadjidinova"
          git config --global user.email "madina.tadjidinova@gmail.com"

      - name: Push Helm Chart
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MY_TOKEN }}
          publish_dir: output/
